### ISSUE TITLE
jQuery initial API call buildout

### ISSUE THREAD

**Issue by natemking** [natemking/shop_n_chef#4]
jQuery initial API call buildout

**Comment by natemking** [comment]
Spoonacular API calls setup in recipe.js. First call is dependent on the users search terms. The call populates 10 options returned from the API. The user can then click on one of those 10 and will be presented with that recipes ingredients and instructions.

**Comment by preussenfahrer** [comment]
User now has a fresh set of options after searching for a new ingredient.

**Comment by preussenfahrer** [comment]
I added some functionality for the user to input an ingredient and then be presented with up to ten recipes for each ingredient. Recipes are also presented with their image next to the required ingredients, and an instructions section which shows them how to prepare the recipe
